// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySuperStats.WebApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MySuperStats.WebApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190906123147_AddNewRolesClaims")]
    partial class AddNewRolesClaims
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CustomFramework.WebApiUtils.Identity.Models.ClientApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientApplicationCode")
                        .IsRequired()
                        .HasColumnName("client_application_code")
                        .HasMaxLength(6);

                    b.Property<string>("ClientApplicationName")
                        .IsRequired()
                        .HasColumnName("client_application_name")
                        .HasMaxLength(20);

                    b.Property<string>("ClientApplicationPassword")
                        .IsRequired()
                        .HasColumnName("client_application_password")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnName("security_stamp")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_client_applications");

                    b.HasIndex("ClientApplicationCode")
                        .HasName("ix_client_applications_client_application_code");

                    b.HasIndex("ClientApplicationName")
                        .HasName("ix_client_applications_client_application_name");

                    b.HasIndex("Status")
                        .HasName("ix_client_applications_status");

                    b.HasIndex("ClientApplicationCode", "ClientApplicationPassword")
                        .HasName("ix_client_applications_client_application_code_client_applicat~");

                    b.ToTable("client_applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientApplicationCode = "web",
                            ClientApplicationName = "web",
                            ClientApplicationPassword = "8ohVCPHTYZ3pYrhIBhLYSyiDkYbiKiA7AcRpvkuIOls=",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            SecurityStamp = "nFOhCb4zVdFj8N/aJxnIVA==",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasName("ix_role_claims_role_id");

                    b.ToTable("role_claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "OnlySystemAdmin",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "CreateBasketballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "UpdateBasketballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "DeleteBasketballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "CreateFootballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "UpdateFootballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "DeleteFootballStat",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "CreateMatch",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "UpdateMatch",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "DeleteMatch",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "CreateMatchGroup",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "UpdateMatchGroup",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "DeleteMatchGroup",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "SelectMatchGroup",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "CreateMatchGroupTeam",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "DeleteMatchGroupTeam",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "CreateTeam",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "DeleteTeam",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "CreateMatchGroupUser",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "DeleteMatchGroupUser",
                            ClaimValue = "true",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "CreateBasketballStat",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "CreateFootballStat",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "CreateMatch",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "UpdateMatch",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "CreateMatchGroupUser",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "DeleteMatchGroupUser",
                            ClaimValue = "true",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "CreateBasketballStat",
                            ClaimValue = "true",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "CreateFootballStat",
                            ClaimValue = "true",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "CreateMatch",
                            ClaimValue = "true",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "UpdateMatch",
                            ClaimValue = "true",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasName("ix_user_claims_user_id");

                    b.ToTable("user_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasName("ix_user_logins_user_id");

                    b.ToTable("user_logins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.BasketballStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Assist")
                        .HasColumnName("assist")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<decimal>("Interrupt")
                        .HasColumnName("interrupt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LooseBall")
                        .HasColumnName("loose_ball")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MatchId")
                        .HasColumnName("match_id");

                    b.Property<decimal>("MissingOnePoint")
                        .HasColumnName("missing_one_point")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MissingTwoPoint")
                        .HasColumnName("missing_two_point")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OnePoint")
                        .HasColumnName("one_point")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rebound")
                        .HasColumnName("rebound")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<decimal>("StealBall")
                        .HasColumnName("steal_ball")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TeamId")
                        .HasColumnName("team_id");

                    b.Property<decimal>("TwoPoint")
                        .HasColumnName("two_point")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_basketball_stats");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_basketball_stats_create_user_id");

                    b.HasIndex("Status")
                        .HasName("ix_basketball_stats_status");

                    b.HasIndex("TeamId")
                        .HasName("ix_basketball_stats_team_id");

                    b.HasIndex("UserId")
                        .HasName("ix_basketball_stats_user_id");

                    b.HasIndex("MatchId", "UserId", "TeamId")
                        .HasName("ix_basketball_stats_match_id_user_id_team_id");

                    b.ToTable("basketball_stats");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.FootballStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Assist")
                        .HasColumnName("assist")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ConcedeGoal")
                        .HasColumnName("concede_goal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<decimal>("Goal")
                        .HasColumnName("goal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MatchId")
                        .HasColumnName("match_id");

                    b.Property<decimal>("MissedPenalty")
                        .HasColumnName("missed_penalty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OwnGoal")
                        .HasColumnName("own_goal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PenaltyScore")
                        .HasColumnName("penalty_score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaveGoal")
                        .HasColumnName("save_goal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_football_stats");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_football_stats_create_user_id");

                    b.HasIndex("Status")
                        .HasName("ix_football_stats_status");

                    b.HasIndex("TeamId")
                        .HasName("ix_football_stats_team_id");

                    b.HasIndex("UserId")
                        .HasName("ix_football_stats_user_id");

                    b.HasIndex("MatchId", "UserId", "TeamId")
                        .HasName("ix_football_stats_match_id_user_id_team_id");

                    b.ToTable("football_stats");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeamId")
                        .HasColumnName("away_team_id");

                    b.Property<decimal>("AwayTeamScore")
                        .HasColumnName("away_team_score");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnName("duration_in_minutes");

                    b.Property<int>("HomeTeamId")
                        .HasColumnName("home_team_id");

                    b.Property<decimal>("HomeTeamScore")
                        .HasColumnName("home_team_score");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnName("match_date");

                    b.Property<int>("MatchGroupId")
                        .HasColumnName("match_group_id");

                    b.Property<int>("Order")
                        .HasColumnName("order");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.Property<string>("VideoLink")
                        .HasColumnName("video_link")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("AwayTeamId")
                        .HasName("ix_matches_away_team_id");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_matches_create_user_id");

                    b.HasIndex("HomeTeamId")
                        .HasName("ix_matches_home_team_id");

                    b.HasIndex("MatchGroupId")
                        .HasName("ix_matches_match_group_id");

                    b.HasIndex("Status")
                        .HasName("ix_matches_status");

                    b.HasIndex("MatchDate", "Order")
                        .HasName("ix_matches_match_date_order");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.MatchGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnName("group_name")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_match_groups");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_match_groups_create_user_id");

                    b.HasIndex("GroupName")
                        .HasName("ix_match_groups_group_name");

                    b.HasIndex("Status")
                        .HasName("ix_match_groups_status");

                    b.ToTable("match_groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            GroupName = "Provus Basketbol",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.MatchGroupTeam", b =>
                {
                    b.Property<int>("MatchGroupId")
                        .HasColumnName("match_group_id");

                    b.Property<int>("TeamId")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.HasKey("MatchGroupId", "TeamId")
                        .HasName("pk_match_group_teams");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_match_group_teams_create_user_id");

                    b.HasIndex("Status")
                        .HasName("ix_match_group_teams_status");

                    b.HasIndex("TeamId")
                        .HasName("ix_match_group_teams_team_id");

                    b.ToTable("match_group_teams");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.MatchGroupUser", b =>
                {
                    b.Property<int>("MatchGroupId")
                        .HasColumnName("match_group_id");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.HasKey("MatchGroupId", "UserId")
                        .HasName("pk_match_group_users");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_match_group_users_create_user_id");

                    b.HasIndex("Status")
                        .HasName("ix_match_group_users_status");

                    b.HasIndex("UserId")
                        .HasName("ix_match_group_users_user_id");

                    b.ToTable("match_group_users");

                    b.HasData(
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 1,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 1,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 2,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 2,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 3,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 3,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 4,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 4,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 5,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 5,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 6,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 6,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 7,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 7,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 8,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 8,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 9,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 9,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 10,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 10,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 11,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 11,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 12,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 12,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 13,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 13,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 14,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 14,
                            Status = 1
                        },
                        new
                        {
                            MatchGroupId = 1,
                            UserId = 15,
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Id = 15,
                            Status = 1
                        });
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnName("normalized_name")
                        .HasMaxLength(256);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("role_name_index");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "00958741-c4fe-49a9-88d0-4dd0b3281af0",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "b0fcbb8b-21ee-4c30-b910-0154b507da3f",
                            Name = "GroupAdmin",
                            NormalizedName = "GROUPADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "97eb3d23-d1b6-479e-9579-8adb1a5cbbfa",
                            Name = "Editor",
                            NormalizedName = "EDITOR",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "7539a5c2-fd47-4c9a-8ecc-b425d2983afe",
                            Name = "Player",
                            NormalizedName = "PLAYER",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnName("color")
                        .HasMaxLength(25);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(25);

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("CreateUserId")
                        .HasName("ix_teams_create_user_id");

                    b.HasIndex("Name")
                        .HasName("ix_teams_name");

                    b.HasIndex("Status")
                        .HasName("ix_teams_status");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnName("birth_date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnName("create_date_time");

                    b.Property<int>("CreateUserId")
                        .HasColumnName("create_user_id");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnName("delete_date_time");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("LastLogOutDate")
                        .HasColumnName("last_log_out_date");

                    b.Property<DateTime>("LastTokenDate")
                        .HasColumnName("last_token_date");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnName("normalized_email")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnName("normalized_user_name")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .HasColumnName("surname");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnName("update_date_time");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnName("update_user_id");

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasMaxLength(256);

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("user_name_index");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1982, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yunusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "YUNUS EMRE",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUNUSEMRE@GMAIL.COM",
                            NormalizedUserName = "YUNUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "KIRKANAHTAR",
                            TwoFactorEnabled = false,
                            UserName = "yunusemre@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1975, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "y.unusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ALİ",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "Y.UNUSEMRE@GMAIL.COM",
                            NormalizedUserName = "Y.UNUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "YUNUSLAR",
                            TwoFactorEnabled = false,
                            UserName = "y.unusemre@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1975, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "y..unusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ARBAK",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "Y..UNUSEMRE@GMAIL.COM",
                            NormalizedUserName = "Y..UNUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "DEMİRDAĞ",
                            TwoFactorEnabled = false,
                            UserName = "y..unusemre@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1970, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "y...unusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "FAHRİ",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "Y...UNUSEMRE@GMAIL.COM",
                            NormalizedUserName = "Y...UNUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "SÖYLEMEZGİLLER",
                            TwoFactorEnabled = false,
                            UserName = "y...unusemre@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1982, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yu.nusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "MAHMUT",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YU.NUSEMRE@GMAIL.COM",
                            NormalizedUserName = "YU.NUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "BALCİ",
                            TwoFactorEnabled = false,
                            UserName = "yu.nusemre@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1971, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yu..nusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "İLKER",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YU..NUSEMRE@GMAIL.COM",
                            NormalizedUserName = "YU..NUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "OYMAN",
                            TwoFactorEnabled = false,
                            UserName = "yu..nusemre@gmail.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1984, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yu...nusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "GÜRCAN",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YU...NUSEMRE@GMAIL.COM",
                            NormalizedUserName = "YU...NUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "ATEŞ",
                            TwoFactorEnabled = false,
                            UserName = "yu...nusemre@gmail.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1988, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yun.usemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "CEYHAN",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUN.USEMRE@GMAIL.COM",
                            NormalizedUserName = "YUN.USEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "GÖNEN",
                            TwoFactorEnabled = false,
                            UserName = "yun.usemre@gmail.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1970, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yun..usemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "AHMET",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUN..USEMRE@GMAIL.COM",
                            NormalizedUserName = "YUN..USEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "OKÇULAR",
                            TwoFactorEnabled = false,
                            UserName = "yun..usemre@gmail.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1973, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yun...usemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "MEHMET",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUN...USEMRE@GMAIL.COM",
                            NormalizedUserName = "YUN...USEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "AYGÜN",
                            TwoFactorEnabled = false,
                            UserName = "yun...usemre@gmail.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1987, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yunu.semre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "FIRAT",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUNU.SEMRE@GMAIL.COM",
                            NormalizedUserName = "YUNU.SEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "TİMUR",
                            TwoFactorEnabled = false,
                            UserName = "yunu.semre@gmail.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yunus.emre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "GÖKAY",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUNUS.EMRE@GMAIL.COM",
                            NormalizedUserName = "YUNUS.EMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "PATAR",
                            TwoFactorEnabled = false,
                            UserName = "yunus.emre@gmail.com"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1989, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "yunusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ALTUĞ",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "YUNUSE.MRE@GMAIL.COM",
                            NormalizedUserName = "YUNUSE.MRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "DEMİRSEL",
                            TwoFactorEnabled = false,
                            UserName = "yunuse.mre@gmail.com"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2000, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "y.u.nusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "ÖMER",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "Y.U.NUSEMRE@GMAIL.COM",
                            NormalizedUserName = "Y.U.NUSEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "SEFER",
                            TwoFactorEnabled = false,
                            UserName = "y.u.nusemre@gmail.com"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1987, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ca40583b-394d-48a0-879e-c11a21da1aeb",
                            CreateDateTime = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 1,
                            Email = "y.u.n.usemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "CANER",
                            LastLogOutDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTokenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = true,
                            NormalizedEmail = "Y.U.N.USEMRE@GMAIL.COM",
                            NormalizedUserName = "Y.U.N.USEMRE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF8ox4odFYBEgV+2mBcGv8jw4KXJKnjayRE9pJ91NG8Yp+9uSVMx6QU7TP2M9MOCGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABQONVFKVTNPYSRLSGOFKH5KNSVIANUW",
                            Status = 1,
                            Surname = "PAZAR",
                            TwoFactorEnabled = false,
                            UserName = "y.u.n.usemre@gmail.com"
                        });
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnName("role_id");

                    b.Property<int>("MatchGroupId")
                        .HasColumnName("match_group_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasName("ix_user_roles_role_id");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            MatchGroupId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_role_claims_roles_role_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_claims_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_logins_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_tokens_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.BasketballStat", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.Match", "Match")
                        .WithMany("BasketballStats")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("fk_basketball_stats_matches_match_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.Team", "Team")
                        .WithMany("BasketballStats")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_basketball_stats_teams_team_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.User", "User")
                        .WithMany("BasketballStats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_basketball_stats_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.FootballStat", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.Match", "Match")
                        .WithMany("FootballStats")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("fk_football_stats_matches_match_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.Team", "Team")
                        .WithMany("FootballStats")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_football_stats_teams_team_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.User", "User")
                        .WithMany("FootballStats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_football_stats_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.Match", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .HasConstraintName("fk_matches_teams_away_team_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .HasConstraintName("fk_matches_teams_home_team_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.MatchGroup", "MatchGroup")
                        .WithMany("Matches")
                        .HasForeignKey("MatchGroupId")
                        .HasConstraintName("fk_matches_match_groups_match_group_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.MatchGroupTeam", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.MatchGroup", "MatchGroup")
                        .WithMany("MatchGroupTeams")
                        .HasForeignKey("MatchGroupId")
                        .HasConstraintName("fk_match_group_teams_match_groups_match_group_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.Team", "Team")
                        .WithMany("MatchGroupTeams")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_match_group_teams_teams_team_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.MatchGroupUser", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.MatchGroup", "MatchGroup")
                        .WithMany("MatchGroupUsers")
                        .HasForeignKey("MatchGroupId")
                        .HasConstraintName("fk_match_group_users_match_groups_match_group_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.User", "User")
                        .WithMany("MatchGroupUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_match_group_users_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MySuperStats.WebApi.Models.UserRole", b =>
                {
                    b.HasOne("MySuperStats.WebApi.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_user_roles_roles_role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySuperStats.WebApi.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_roles_users_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
